# Generated by Django 2.2.7 on 2020-01-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('congenial', models.CharField(max_length=30)),
                ('age_group', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=30)),
                ('causes', models.CharField(max_length=30)),
                ('prevention', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
            ],
        ),
    ]
