# Generated by Django 2.2.7 on 2020-01-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('blood_group', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('allergy', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('preExisting', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='disease',
            name='age_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='causes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='classification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='congenial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.CharField(max_length=50),
        ),
    ]
