# Generated by Django 2.2.7 on 2020-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_auto_20200123_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history',
            field=models.CharField(default='Cancer', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
